sudo: required
services:
  - docker

before_install:
  - docker build -t muhsenmaqsudi/vue-docker -f Dockerfile.dev .

script:
  - docker run -t muhsenmaqsudi/vue-docker npm run test:unit

# deploy:
#   provider: script