version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      - CHOKIDAR_USEPOLLING=true #vue hot reloading
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "test:unit:watch"]
    